repos:
# Run the Ruff linter.
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.3
  hooks:
    # Run the Ruff linter.
    - id: ruff
    # Run the Ruff formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-toml
    - id: fix-encoding-pragma
    - id: mixed-line-ending
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
      # I like to run in strict mode usually but we can only do it after we have
      # type annotations consistently everywhere. We should later add:
      #args: [--strict, --ignore-missing-imports]
      # second is default that needs to be reproduced with explicitly given args
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: master  # or specific git tag
  hooks:
    - id: markdownlint # Configure in .mdlrc
      files: "content/"
