repos:
# Run the Ruff linter.
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.3
  hooks:
    # Run the Ruff linter.
    - id: ruff
    # Run the Ruff formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-toml
    - id: fix-encoding-pragma
    - id: mixed-line-ending
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
